# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import blog_pb2 as blog__pb2


class BlogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryPost = channel.unary_unary(
                '/BlogService/QueryPost',
                request_serializer=blog__pb2.PostRequest.SerializeToString,
                response_deserializer=blog__pb2.PostResponse.FromString,
                )
        self.ListPosts = channel.unary_unary(
                '/BlogService/ListPosts',
                request_serializer=blog__pb2.ListPostRequest.SerializeToString,
                response_deserializer=blog__pb2.ListPostResponse.FromString,
                )


class BlogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryPost': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPost,
                    request_deserializer=blog__pb2.PostRequest.FromString,
                    response_serializer=blog__pb2.PostResponse.SerializeToString,
            ),
            'ListPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPosts,
                    request_deserializer=blog__pb2.ListPostRequest.FromString,
                    response_serializer=blog__pb2.ListPostResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BlogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlogService/QueryPost',
            blog__pb2.PostRequest.SerializeToString,
            blog__pb2.PostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlogService/ListPosts',
            blog__pb2.ListPostRequest.SerializeToString,
            blog__pb2.ListPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
